version: '2'
services:
    kompeteer-app:
        image: kompeteer
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://kompeteer-postgresql:5432/kompeteer
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kompeteer-postgresql:
        extends:
            file: postgresql.yml
            service: kompeteer-postgresql
